home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('contact/', views.ContactUsView.as_view(), name="contact"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
]

metaClinic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('profile/', include('user.urls', namespace='profile')),
    path("__debug__/", include("debug_toolbar.urls")),

]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('<int:doctor_id>/', views.ProfileView.as_view(), name='profile'),
    path('patientlist/<int:doctor_id>/', views.PatientListView.as_view(), name='patientlist'),
    path('appointmentlist/<int:doctor_id>/', views.AppointmentListView.as_view(), name='appointmentlist'),
]

home/models.py
from django.db import models
from PIL import Image
from user.models import Patient, Doctor


class AboutUs(models.Model):
    email = models.EmailField()
    bio = models.TextField()
    phone = models.CharField(max_length=15, null=False, blank=False, unique=True)
    address = models.TextField(null=False)
    github = models.URLField(null=False, blank=False)
    linkedin = models.URLField(null=True, blank=False)
    instagram = models.URLField(null=True, blank=False)
    telegram = models.URLField(null=True, blank=False)

    def __str__(self):
        return self.bio


class Team(models.Model):
    full_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length=15, unique=True)
    nick_name = models.CharField(max_length=50, unique=True)
    position = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='images/')
    instagram = models.URLField(null=True, blank=True)
    telegram = models.URLField(null=True, blank=True)
    github = models.URLField(null=True, blank=True)
    linkedin = models.URLField(null=True, blank=True)
    site = models.URLField(null=True, blank=True)

    def save(self, *args, **kwargs):
        super(Team, self).save(*args, **kwargs)

        if self.image:
            with Image.open(self.image.path) as img:
                image = img.resize((350, 350))
                image.save(self.image.path)

    def __str__(self):
        return self.full_name


class Pricing(models.Model):
    title = models.CharField(max_length=10, unique=True)
    description = models.TextField()
    price = models.IntegerField()
    count = models.IntegerField()
    active_email = models.IntegerField()
    module = models.IntegerField()
    automatic_scan = models.IntegerField()
    parallel_scan = models.IntegerField()

    def __str__(self):
        return self.title


class ContactUsMessage(models.Model):
    name = models.CharField(max_length=100, null=False)
    email = models.EmailField(null=False)
    phone = models.CharField(max_length=15, null=False, blank=False)
    subject = models.CharField(max_length=100, null=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"from: {self.name}-{self.email}\nsubject: {self.message[:10]}"


class MedicalHistory(models.Model):
    ID = models.AutoField(primary_key=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='medicalhistories')
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='medicalhistories')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    notes = models.TextField()
    files = models.FileField(upload_to=f'documents/{patient}-{doctor}')

    def __str__(self):
        return f'{self.patient} - {self.doctor}'

class Appointment(models.Model):
    ID = models.AutoField(primary_key=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='appointments')
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='appointments')
    medicalhistory = models.ForeignKey(MedicalHistory, on_delete=models.CASCADE, related_name='appointments', null=True, blank=True)
    date = models.DateField()
    time = models.TimeField()
    reason = models.TextField()
    notes = models.TextField()

    def __str__(self):
        return f'{self.patient} - {self.date} - {self.time}'

class Prescription(models.Model):
    ID = models.AutoField(primary_key=True)
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE, related_name='prescriptions')
    drugs = models.TextField()
    recipe = models.TextField()

    def __str__(self):
        return f'{self.drugs}'

class Bill(models.Model):
    ID = models.AutoField(primary_key=True)
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE, related_name='bills')
    price = models.DecimalField(max_digits=10, decimal_places=0)
    date = models.DateTimeField(auto_now_add=True)
    time = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)


    def __str__(self):
        return f'{self.appointment} - {self.price} - {self.status}'

home/forms.py
from django import forms
from django.core.validators import RegexValidator, MaxLengthValidator, MinLengthValidator
from .models import ContactUsMessage
from django.db import models

password_validator = RegexValidator(
    regex=r"^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$",
    message='Minimum eight characters, at least one letter, one number and one special character:',
    code='invalid_password'
)


class RegistrationForm(forms.Form):
    username = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={'placeholder': 'Enter your username'}),
    )
    email = forms.EmailField(
        label="",
        widget=forms.EmailInput(attrs={'placeholder': 'Enter your email'}),
    )
    password1 = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password'}),
        validators=[password_validator, MinLengthValidator(8), MaxLengthValidator(30)]
    )
    password2 = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirm your password'}),
    )


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactUsMessage
        fields = ['name', 'email', 'phone', 'message']

home/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy
from .forms import RegistrationForm, ContactForm
from .models import Team, Pricing
from user.models import Doctor


def home(request):
    teams = Team.objects.all()
    pricing = Pricing.objects.all()
    return render(request, 'home.html', {"header": True, "footer": True, "teams": teams, "pricing": pricing})

@method_decorator(csrf_exempt, name='dispatch')
class SignupView(View):
    form_class = RegistrationForm
    template_name = 'login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'You have already registered!!', 'warning')
            return redirect('home:home')
        else:
            return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['password1'] != cd['password2']:
                messages.error(request, 'Password and confirm password do not match!', extra_tags="danger")
                return redirect('home:login')

            # Create the user
            user = Doctor.objects.create_user(
                username=cd['username'],
                email=cd['email'],
                password=cd['password1']
            )
            messages.success(request, 'Account created successfully!', 'success')
            return redirect('home:home')

        return render(request, self.template_name, {'form': form})




@method_decorator(csrf_exempt, name='dispatch')
class LoginView(View):
    form_class = AuthenticationForm
    template_name = 'login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'You have already logged in', 'warning')
            return redirect('home:home')
        else:
            return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                messages.success(request, f"Welcome back, {username}!", 'success')
                return redirect('home:home')
            else:
                messages.error(request, "Invalid username or password.")
                redirect('login')
        return render(request, self.template_name, {'form': form})

class LogoutView(View):

    def get(self, request):
        logout(request)
        messages.success(request, 'You have been logged out successfully!', 'success')
        return redirect(reverse_lazy('home:login'))


@method_decorator(csrf_exempt, name='dispatch')
class ContactUsView(View):
    form_class = ContactForm
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            response_data = {'status': 'success', 'message': 'Your message has been sent.'}
            return JsonResponse(response_data)
        else:
            response_data = {'status': 'error', 'message': form.errors}
            return JsonResponse(response_data)

        response_data = {'status': 'error', 'message': 'Invalid request method.'}
        return JsonResponse(response_data)

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
     <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">   
   
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Basic Library -->
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    {% block style %} {% endblock %}

    <title>{% block title %} {% endblock %} </title>

</head>
<body id="page-top" class="politics_version">
    
    {% if header %}
        {% include 'header.html' %}
    {% endif %}
    {% include 'messages.html' %}

    {% block body %} {% endblock %}
    
    {% if footer %}
        {% include 'footer.html' %}
    {% endif %}
</body>
</html>

home/templates/footer.html
{% load static %}
<section id="home" class="main-banner parallaxie" style="background: url({% static 'images/banner.jpg' %}); height: fit-content !important ">
<div class="" style="color: #fff; display: table-cell; position: relative; z-index: 1;">
    <div class="container">
        <div class="footer-distributed">
            <a href="#"><img src="{% static 'images/logo1.png' %}" alt="MetaScanner"/></a>
            <div class="footer-center">
                <p class="footer-links">
                    <a href="#">Home</a>
                    <a href="#pricing">Pricing</a>
                    <a href="#about">About</a>
                    <a href="">
                        <del>FaQ</del>
                    </a>
                    <a href="#contact">Contact</a>
                </p>
                <p class="footer-company-name">All Rights Reserved. &copy; 2024 <a href="#">Meta Scanner</a> Design By :
                    <a>Legend</a></p>
            </div>
        </div>
    </div><!-- end container -->
</div><!-- end copyrights -->

<a href="#" id="scroll-to-top" class="dmtop global-radius"><i class="fa fa-angle-up"></i></a>

<!-- ALL JS FILES -->
<script src="{% static 'js/all.js' %}"></script>
<!-- Camera Slider -->
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/parallaxie.js' %}"></script>
<script src="{% static 'js/headline.js' %}"></script>
<!-- Contact form JavaScript -->
<script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
<script src="{% static 'js/contact_me.js' %}"></script>
<!-- ALL PLUGINS -->
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/jquery.vide.js' %}"></script>

home/templates/header.html
{% load static %}
<!-- LOADER -->
<div id="preloader">
    <div id="main-ld">
        <div id="loader"></div>
    </div>
</div><!-- end loader -->
<!-- END LOADER -->

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">
            <img class="img-fluid" src="{% static 'images/logo1.png' %}" alt=""/>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ml-auto">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger active" href="#home">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#about">About us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#services">Services</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#team">Our Team</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#pricing">Pricing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#contact">Contact Us</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

home/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %} Home Page | MetaScanner App {% endblock %}

{% block style %}
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon"/>
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/camera.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/prettyPhoto.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="{% static 'js/modernizr.js' %}"></script> <!-- Modernizr -->

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
{% endblock %}

{% block body %}
    	<section id="home" class="main-banner parallaxie" style="background: url({% static 'images/banner.jpg' %})">
		<div class="heading">
			<h1>Welcome to META Clinic</h1>
			<h3 class="cd-headline clip is-full-width">
				<span></span>
				<span class="cd-words-wrapper">
					<b class="is-visible">Health care Starts Here!</b>
					<b>Your health is our priority</b>
					<b>Mind Your health, Mind Your Life</b>
					<b>Excellence in Health Services</b>
				</span>
				<div class="btn-ber">
                    {% if user.is_authenticated %}
                        <a class="get_btn hvr-bounce-to-top" href="{% url 'user:profile' request.user.ID %}">Profile</a>
                    {% else %}
                        <a class="get_btn hvr-bounce-to-top" href="{% url 'home:login' %}">Get started</a>
                    {% endif %}
					<a class="learn_btn hvr-bounce-to-top" href="#services">Learn More</a>
				</div>
			</h3>
		</div>
	</section>

    <div id="about" class="section wb">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="message-box">
                        <h2>Welcome to META Scanner</h2>
                        <p> Integer rutrum ligula eu dignissim laoreet. Pellentesque venenatis nibh sed tellus faucibus bibendum. Sed fermentum est vitae rhoncus molestie. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed vitae rutrum neque. Ut id erat sit amet libero bibendum aliquam. Donec ac egestas libero, eu bibendum risus. Phasellus et congue justo. </p>

                        <a href="#contact" class="sim-btn hvr-bounce-to-top js-scroll-trigger"><span>Contact Us</span></a>
                    </div><!-- end messagebox -->
                </div><!-- end col -->

                <div class="col-md-6">
                    <div class="right-box-pro wow fadeIn">
                        <img src="{% static 'images/about.png' %}" alt="" class="img-fluid img-rounded">
                    </div><!-- end media -->
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->

    <div id="services" class="section lb">
        <div class="container">
            <div class="section-title text-center">
                <h3>Services</h3>
                <p>Quisque eget nisl id nulla sagittis auctor quis id. Aliquam quis vehicula enim, non aliquam risus.</p>
            </div><!-- end title -->

            <div class="row">
				<div class="col-md-4">
                    <div class="services-inner-box">
						<div class="ser-icon">
							<i class="flaticon-seo"></i>
						</div>
						<h2>Web Development</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					</div>
                </div><!-- end col -->
                <div class="col-md-4">
                    <div class="services-inner-box">
						<div class="ser-icon">
							<i class="flaticon-development"></i>
						</div>
						<h2>Responsive Design</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					</div>
                </div><!-- end col -->
				<div class="col-md-4">
                    <div class="services-inner-box">
						<div class="ser-icon">
							<i class="flaticon-process"></i>
						</div>
						<h2>Creative Design</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					</div>
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->

	<div id="team" class="section wb">
		<div class="container">
			<div class="section-title text-center">
				<h3>Our Team</h3>
				<p>Quisque eget nisl id nulla sagittis auctor quis id. Aliquam quis vehicula enim, non aliquam risus.</p>
			</div><!-- end title -->

			<div class="row">
				{% for team in teams %}
                    <div class="col-md-4 col-sm-6">
                        <div class="our-team">
                            <div class="pic">
                                <img src="{% static team.image %}">
                            </div>
                            <div class="team-content">
                                <h3 class="title">{{ team.full_name }}
                                    {#                                    show nick name #}
                                    {% if team.nick_name %}
                                        <br>
                                        <small> {{ team.nick_name }} </small>
                                    {% endif %}
                                </h3>
                                <span class="post">{{ team.position }}</span>
                                <ul class="social">
                                    {% if team.github %}
                                    <li><a href="{{ team.github }}" class="fa fa-github"></a></li>
                                    {% endif %}
                                    {% if team.instagram %}
                                    <li><a href="{{ team.instagram }}" class="fa fa-instagram"></a></li>
                                    {% endif %}
                                    {% if team.linkedin %}
                                    <li><a href="{{ team.linkedin }}" class="fa fa-linkedin"></a></li>
                                    {% endif %}
                                    {% if team.email %}
                                    <li><a href="{{ team.email }}" class="fa fa-envelope"></a></li>
                                    {% endif %}
                                    {% if team.site %}
                                    <li><a href="{{ team.site }}" class="fa fa-bookmark"></a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
			</div>
		</div>
	</div>

	<div id="pricing" class="section lb">
		<div class="container">
			<div class="section-title text-center">
                <h3>Pricing</h3>
                <p>Quisque eget nisl id nulla sagittis auctor quis id. Aliquam quis vehicula enim, non aliquam risus.</p>
            </div><!-- end title -->

			<div class="row">
{% for price in pricing %}
                <div class="col-md-4 col-sm-6">
                    <div class="pricingTable">
                        <svg x="0" y="0" viewBox="0 0 360 220">
                            <g>
                                <path fill="#e98c1b" d="M0.732,193.75c0,0,29.706,28.572,43.736-4.512c12.976-30.599,37.005-27.589,44.983-7.061
                                    c8.09,20.815,22.83,41.034,48.324,27.781c21.875-11.372,46.499,4.066,49.155,5.591c6.242,3.586,28.729,7.626,38.246-14.243
                                    s27.202-37.185,46.917-8.488c19.715,28.693,38.687,13.116,46.502,4.832c7.817-8.282,27.386-15.906,41.405,6.294V0H0.48
                                    L0.732,193.75z"></path>
                            </g>
                            <text transform="matrix(1 0 0 1 69.7256 116.2686)" fill="#fff" font-size="78.4489">${{  price.price }}</text>
{#                            <text transform="matrix(0.9566 0 0 1 197.3096 83.9121)" fill="#fff" font-size="29.0829">.99</text>#}
                            <text transform="matrix(1 0 0 1 233.9629 115.5303)" fill="#fff" font-size="15.4128">/Month</text>
                        </svg>
                        <div class="pricing-content">
                            <h3 class="title">{{ price.title }}</h3>
                            <ul class="pricing-content">
                                <li><b>{{ price.count }}</b> Scan Count</li>
                                <li><b>{{ price.active_email }}</b> Active Email</li>
                                <li><b>{{ price.module }}</b> Module Scan</li>
                                <li><b>{{ price.automatic_scan }}</b> Automatic Scan</li>
                            </ul>
                            <a href="{% if user.is_authenticated %}/price/{{ price.id }}{% else %}/login{% endif %}" class="sim-btn hvr-bounce-to-top pricingTable-signup">Buy Now</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

		</div>
	</div>

    <div id="contact" class="section db">
        <div class="container" style="background: url({% static 'images/1.png' %}) no-repeat center center" >
            <div class="section-title text-center">
                <h3>Contact</h3>
                <p>Quisque eget nisl id nulla sagittis auctor quis id. Aliquam quis vehicula enim, non aliquam risus.</p>
            </div><!-- end title -->

            <div class="row">
                <div class="col-md-12">
                    <div class="contact_form">
                        <div id="message"></div>
{#                        <form action="{% url 'contact' %}" method="post">#}
                        <form id="contactForm" name="sentMessage" novalidate="novalidate" action="" method="post">
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<input name="name" class="form-control" id="name" type="text" placeholder="Your Name" required="required" data-validation-required-message="Please enter your name.">
										<p class="help-block text-danger"></p>
									</div>
									<div class="form-group">
										<input name="email" class="form-control" id="email" type="email" placeholder="Your Email" required="required" data-validation-required-message="Please enter your email address.">
										<p class="help-block text-danger"></p>
									</div>
									<div class="form-group">
										<input name="phone" class="form-control" id="phone" type="tel" placeholder="Your Phone" required="required" data-validation-required-message="Please enter your phone number.">
										<p class="help-block text-danger"></p>
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<textarea name="message" class="form-control" id="message" placeholder="Your Message" required="required" data-validation-required-message="Please enter a message."></textarea>
										<p class="help-block text-danger"></p>
									</div>
								</div>
								<div class="clearfix"></div>
								<div class="col-lg-12 text-center">
									<div id="success"></div>
									<button id="sendMessageButton" class="sim-btn hvr-bounce-to-top" type="submit">Send Message</button>
{#									<button class="sim-btn hvr-bounce-to-top" type="submit">Send Message</button>#}
								</div>
							</div>
						</form>
                    </div>
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->


{% endblock %}

home/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %} MetaScanner | Sign In/Up {% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block body %}
<div id="back" class="main-banner" style="background-image: url("{% static 'images/5079835.jpg' %}");">
    <img src="{% static 'images/logo1.png' %}" alt="Logo">
    <div class="container" id="container">
        <div class="form-container sign-up-container" style="background: url({% static 'images/343660.jpg' %})">
            <form action="{% url 'home:signup' %}" method="post">
                {% csrf_token %}
                <h2>Create Account</h2>
                <div class="social-container">
                    <a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
                    <a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <span>or use your email for registration</span>
                <input type="text" placeholder="Username" required name="username">
                <input type="email" placeholder="Email" required name="email">
                <input type="password" placeholder="Password" required name="password1">
                <input type="password" placeholder="Confirm Password" required name="password2">
                <button type="submit">Sign Up</button>
            </form>
        </div>
        <div class="form-container sign-in-container" style="background: url({% static 'images/343660.jpg' %})">
            <form action="{% url 'home:login' %}" method="post">
                {% csrf_token %}
                <h1>Sign in</h1>
                <div class="social-container">
                    <a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
                    <a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <span>or use your account</span>
                <input type="text" placeholder="Username" name="username" required>
                <input type="password" placeholder="Password" name="password" required>
                <a href="#">Forgot your password?</a>
                <button type="submit">Sign In</button>
            </form>
        </div>
        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <h1>Welcome Back!</h1>
                    <p>To keep connected with us please login with your personal info</p>
                    <button class="ghost" id="signIn">Sign In</button>
                </div>
                <div class="overlay-panel overlay-right">
                    <h1>Hello, Friend!</h1>
                    <p>Enter your personal details and start journey with us</p>
                    <button class="ghost" id="signUp">Sign Up</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/login.js' %}"></script>
{% endblock %}